apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    name: kind-argocd
    namespace: argocd
  source:
    path: apps
    repoURL: 'https://github.com/mobinesh/argocd-app-of-apps'
    targetRevision: HEAD
  project: default
