apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  project: default
  source:
    chart: prometheus
    helm:
     #valueFiles:
     #   - apps/prometheus/values.yaml
      values: |
       pushgateway:
         enabled: false
       prometheus:
          configmap-reload:
            image:
              repository: quay.io/prometheus-operator/prometheus-config-reloader
              tag: v0.67.0
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: '24.1.0'
      #    helm:
      #      valueFiles:
      #        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
