apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  project: default
  source:
    chart: prometheus
    helm:
      values: |
       pushgateway:
         enabled: false
       prometheus:
          image:
              repository: quay.io/prometheus-operator/prometheus-config-reloader
              tag: v0.67.0
       server:
          image:
              repository: quay.io/prometheus/prometheus
              tag: ""
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: '24.1.0'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
